name: res12featcluster-minibatch-onlyconcat-classifier-fc100-TFF-FFF-TTT-FFF-self-uv_dist-att-FFF-FFF-TTT-FFF-out_conv-test_stop-onlyconcat-sine_pe-pre_normF-init_rp-clusters_64
train_dataset: fc100
train_dataset_args: {split: train, aug: lee}
# val_dataset: fc100
# val_dataset_args: {split: train_phase_val, aug: lee}
fs_dataset: fc100
fs_dataset_args: {split: test, aug: lee}
eval_fs_epoch: 1
model: classifier-sideout
model_args:
    encoder: resnet12-featcluster-minibatch-sideout-classifier
    encoder_args:  {
        use_feat_cluster_list: [[{use_feat_cluster: true, feat_cluster_type: 'out_conv', sideout_concat: true}, false, false], [false, false, false], [true, true, true], [false, false, false]],
        use_self_attention_list: [[false, false, false], [false, false, false],[true, true, true],[false, false, false]],
        self_attention_kwargs: {
           head: 8,
           positional_encoding: 'sine',
           attention_loc: 'uv_dist',
           pre_normalize: false,
           },                        
        feat_cluster_kwargs: {
            max_type: 'softmax', 
            cluster_type: 'dynamic-routing', 
            iterations: 1, 
            K: 100.0, 
            num_clusters: 64,
            detach_coeff: true,
            eps: 0.01,
            fix_init: true,
            channels: 64, 
            normalize_input: true, 
            normalize_init: true, 
            show_cur_iter: false, 
            alpha: 1.0, 
            minibatch: 'sculley-like',
            V_count_init: 1.0,
            detach_uv_dist: false,
        },
        feat_cluster_type: 'out_conv', # can be 'input3x3', 'input', 'out_conv', 'out_conv_identity', 'out_conv_another3x3conv'
        out_feat_flatten: true,
        avgpool: true,
    }
    classifier: linear-classifier 
    classifier_args: {n_classes: 60}
    sideout_info: []
batch_size: 128
max_epoch: 100
opt: long # can be long, lee, long-0.01, adam
save_epoch: 5
#visualize_datasets: true